import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "../app/components/Navbar";
import Footer from "./components/Footer";
import adminNavbar from "./DashboardAdmin/Navbar";
import { SessionProvider } from "next-auth/react";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Pulau Pahawang",
  description: "Generated by create next app",
};

export default function RootLayout({
  children, session, pageprops
}: {
  children: React.ReactNode;
  session: any; // Change this to the correct type for the session
  pageprops: any; // Change this to the correct type for pageprops
}) {
  return (
    <html lang="en">
      <body className={`  ${inter.className}`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
